spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yzdd?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#设置mybatis
mybatis:
  mapper-locations: classpath:com/it/shu/mapper/*.xml
